### PR TITLE
Update for odin v0.13.x

### PR DESCRIPTION
**Pull request by ftommasi**
Minor syntax changes for latest odin version

### CODE REVIEW

**Comment by kevinw** [comment]
Thanks so much for sharing these changes!

What do you think about using `rl_` as a prefix instead of `raylib_` to match some of the other bindings out there? Any opinions on explicit vs easier to type?

**Comment by ftommasi** [comment]
My personal preference has always been to be more explicit in my naming. I always prefer the clarity. However if there are a lot of other bindings with the `rl_ ` prefix I don't mind making that change to this PR

**Comment by kevinw** [comment]
Would you like to take over as the maintainer of these bindings? I'm planning on archiving this repository, since I'm not working with them these days.

**Comment by ftommasi** [comment]
Yes I would be okay to take over as maintainer

**Comment by kevinw** [comment]
Sorry, are you still interested? I will change the README to point to your repo if you have one.

**Comment by ftommasi** [comment]
Yes. Go ahead and change the readme. I have a repository with the same name

**Comment by kevinw** [comment]
Cool, I added a link to your repository in the README. I'll close this issue, as I will not be making any more commits to this repo.

**Pull request closed without merging**
